default rockchip-kernel-6.8.4
    label rockchip-kernel-6.8.4
    LINUX  /Image
    FDT    /dtb/rockchip/rk3328-eaidk-310.dtb
    INITRD /uInitrd
    # FDTOVERLAYS overlay-user/spidev-1.dtbo overlay-user/i2c-3.dtbo
	APPEND root=UUID=bd2a6dbf-c55f-4d5e-8738-797e581ee7c9 rootwait rootfstype=ext4 net.ifnames=0  earlycon console=ttyS2,1500000n8 console=tty1 consoleblank=0 loglevel=4

    label rockchip-kernel-6.8.4-wifi-test1
    LINUX  /Image
    FDT    /dtb/rockchip/rk3328-eaidk310-wifi-test1.dtb
    INITRD /uInitrd
    # FDTOVERLAYS overlay-user/spidev-1.dtbo overlay-user/i2c-3.dtbo
    APPEND root=UUID=bd2a6dbf-c55f-4d5e-8738-797e581ee7c9 rootwait rootfstype=ext4 net.ifnames=0  earlycon console=ttyS2,1500000n8 console=tty1 consoleblank=0 loglevel=4

    label rockchip-kernel-6.8.4-st7789-test1
    LINUX  /Image
    FDT    /dtb/rockchip/rk3328-eaidk310-st7789-test1.dtb
    INITRD /uInitrd
    # FDTOVERLAYS overlay-user/spidev-1.dtbo overlay-user/i2c-3.dtbo
    APPEND root=UUID=bd2a6dbf-c55f-4d5e-8738-797e581ee7c9 rootwait rootfstype=ext4 net.ifnames=0  earlycon console=ttyS2,1500000n8 console=tty1 consoleblank=0 loglevel=4

    label rockchip-kernel-6.8.4-wifi-test2
    LINUX  /Image
    FDT    /dtb/rockchip/rk3328-eaidk310-wifi-test2.dtb
    INITRD /uInitrd
    # FDTOVERLAYS overlay-user/spidev-1.dtbo overlay-user/i2c-3.dtbo
    APPEND root=UUID=bd2a6dbf-c55f-4d5e-8738-797e581ee7c9 rootwait rootfstype=ext4 net.ifnames=0  earlycon console=ttyS2,1500000n8 console=tty1 consoleblank=0 loglevel=4

    label rockchip-kernel-6.8.4-st7789-test2-mode3
    LINUX  /Image
    FDT    /dtb/rockchip/rk3328-eaidk310-st7789-test2.dtb
    INITRD /uInitrd
    # FDTOVERLAYS overlay-user/spidev-1.dtbo overlay-user/i2c-3.dtbo
    APPEND root=UUID=bd2a6dbf-c55f-4d5e-8738-797e581ee7c9 rootwait rootfstype=ext4 net.ifnames=0  earlycon console=ttyS2,1500000n8 console=tty1 consoleblank=0 loglevel=4

    label rockchip-kernel-6.8.4-st7789-test3-arduino-init
    LINUX  /Image
    FDT    /dtb/rockchip/rk3328-eaidk310-st7789-test3.dtb
    INITRD /uInitrd
    # FDTOVERLAYS overlay-user/spidev-1.dtbo overlay-user/i2c-3.dtbo
    APPEND root=UUID=bd2a6dbf-c55f-4d5e-8738-797e581ee7c9 rootwait rootfstype=ext4 net.ifnames=0  earlycon console=ttyS2,1500000n8 console=tty1 consoleblank=0 loglevel=4
